version: '3.7'

services:
  mongo:
    image: mongo:3.6.1-jessie
    container_name: mongo
    build:
      context: db
    ports:
      - 27017:27017

  back-end:
    image: backend-api
    container_name: backend-api
    build:
      context: back-end
    ports:
      - 5001:80
    environment:
      ProductstoreDatabaseSettings__ConnectionString: mongodb://mongo:27017
      ProductstoreDatabaseSettings__DatabaseName:  productsstore
    depends_on:
      - mongo
      
  frontend:
    image: ui:v1
    container_name: front-end
    build:
      context: front-end
    ports:
      - 8082:80
    depends_on:
      - back-end
    
         