FROM node:15.14.0-alpine3.10 AS build
WORKDIR  /usr/src/app

COPY ["package.json", "/usr/src/app/"]
RUN npm install

COPY . /usr/src/app
ARG env=prod
RUN npm run build -- --prod

FROM nginx:1.19.9-alpine
COPY --from=build /usr/src/app/dist/ /usr/share/nginx/html
COPY ["./Nginx/nginx-config.conf", "/etc/nginx/conf.d/default.conf"]